query GetUserData {
  user {
    id
    name
    ...ProfileDetails
    posts {
      title
    }
  }
}

query GetUserData {
  accounts {
    username
    email
  }
}

fragment UserStats on User {
  activityScore
  ...ActivityMetrics
  lastLogin
}

fragment ProfileDetails on User {
  avatar
  bio
}